spring:
  datasource:
    url: ${DB_ANALYTICS_URL:jdbc:postgresql://localhost:5432/healthsync_db}
    username: postgres
    password: subha@#1306
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.healthsync: INFO
    org.springframework: WARN
