spring:
  datasource:
    url: jdbc:postgresql://ep-curly-pond-aoh5ia3m-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_PnifFQ92OAoB&sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_PnifFQ92OAoB
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.healthsync: INFO
    org.springframework: WARN
